# Generated by Django 4.0.5 on 2022-06-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_types', models.CharField(help_text='Enter car type', max_length=200, verbose_name='Car type')),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_types', models.CharField(help_text='Enter fuel type', max_length=200, verbose_name='Fuel type')),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(help_text='Enter car maker name', max_length=200, verbose_name='Car maker')),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_types', models.CharField(help_text='Enter transmission type', max_length=200, verbose_name='Transmission type')),
            ],
        ),
        migrations.CreateModel(
            name='MakerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Enter car model', max_length=200, verbose_name='Model')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='car_type', to='auto_trader_app.cartype')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='maker_models', to='auto_trader_app.maker')),
            ],
        ),
        migrations.CreateModel(
            name='CarAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(help_text='Enter price', verbose_name='Price')),
                ('car_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_model', to='auto_trader_app.makermodel')),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_type', to='auto_trader_app.fueltype')),
                ('transmission_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmission_type', to='auto_trader_app.transmissiontype')),
            ],
        ),
    ]
