# Generated by Django 4.0.5 on 2022-06-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trader_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='year',
            field=models.CharField(default='', help_text='Enter car manufactured year', max_length=4, verbose_name='Year'),
        ),
    ]
