# Generated by Django 4.0.5 on 2022-06-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trader_app', '0002_carad_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='year',
            field=models.CharField(default='Year', help_text='Enter car manufactured year', max_length=4, verbose_name='Year'),
        ),
    ]
