# Generated by Django 4.0.5 on 2022-07-26 16:49

import auto_trader_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trader_app', '0003_alter_carad_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carad',
            options={'verbose_name': 'Car ad', 'verbose_name_plural': 'Car ads'},
        ),
        migrations.AlterModelOptions(
            name='cartype',
            options={'ordering': ['car_types'], 'verbose_name': 'Car type', 'verbose_name_plural': 'Car types'},
        ),
        migrations.AlterModelOptions(
            name='fueltype',
            options={'ordering': ['fuel_types'], 'verbose_name': 'Fuel type', 'verbose_name_plural': 'Fuel types'},
        ),
        migrations.AlterModelOptions(
            name='maker',
            options={'ordering': ['maker'], 'verbose_name': 'Car maker', 'verbose_name_plural': 'Car makers'},
        ),
        migrations.AlterModelOptions(
            name='makermodel',
            options={'ordering': ['maker', 'model'], 'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='transmissiontype',
            options={'ordering': ['transmission_types'], 'verbose_name': 'Transmission type', 'verbose_name_plural': 'Transmission types'},
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_model', to='auto_trader_app.makermodel', verbose_name='car model'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='fuel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_type', to='auto_trader_app.fueltype', verbose_name='fuel type'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='transmission_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmission_type', to='auto_trader_app.transmissiontype', verbose_name='transmission type'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=auto_trader_app.models.get_image_filename, verbose_name='Image')),
                ('car_ad', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_trader_app.carad')),
            ],
        ),
    ]
